name: yeungn's
url: 'https://yeungndev.github.io'
description: 'brain dump'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown
kramdown:
  input: GFM

author: 'yeungn'
disqus_shortname: yeungndev-github-io
google_analytics: UA-109542383-1

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed

permalink: /:title
