name: yeungn's
url: 'https://yeungndev.github.io'
description: 'brain dump'

markdown: kramdown
kramdown:
  input: GFM

author: 'yeungn'
disqus_shortname: yeungndev-github-io
google_analytics: UA-109542383-1

gems:
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed

permalink: /:title
